### ISSUE TITLE
Add a Code of Conduct File

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/CollegeAada#2]
Add a simple code of code file

**Comment by 96RadhikaJadhav** [comment]
@Tejas1510  Can I work on the issue?

**Comment by nilisha-jais** [comment]
I want to work on this issue

**Comment by Tejas1510** [comment]
Go ahead @nilisha-jais

**Comment by kanishkaa24** [comment]
Hey, Can I work on this issue?

**Comment by Tejas1510** [comment]
@kanishkaa24 This issue is solved now
